//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace consultarVentas.wsVenta {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsVentaSoap", Namespace="http://tempuri.org/")]
    public partial class wsVenta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback buscarVentaPorEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarVentaPorFechaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsVenta() {
            this.Url = global::consultarVentas.Properties.Settings.Default.consultarVentas_wsVenta_wsVenta;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event buscarVentaPorEmpresaCompletedEventHandler buscarVentaPorEmpresaCompleted;
        
        /// <remarks/>
        public event buscarVentaPorFechaCompletedEventHandler buscarVentaPorFechaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarVentaPorEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarVentaPorEmpresa(string empresa) {
            object[] results = this.Invoke("buscarVentaPorEmpresa", new object[] {
                        empresa});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarVentaPorEmpresaAsync(string empresa) {
            this.buscarVentaPorEmpresaAsync(empresa, null);
        }
        
        /// <remarks/>
        public void buscarVentaPorEmpresaAsync(string empresa, object userState) {
            if ((this.buscarVentaPorEmpresaOperationCompleted == null)) {
                this.buscarVentaPorEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarVentaPorEmpresaOperationCompleted);
            }
            this.InvokeAsync("buscarVentaPorEmpresa", new object[] {
                        empresa}, this.buscarVentaPorEmpresaOperationCompleted, userState);
        }
        
        private void OnbuscarVentaPorEmpresaOperationCompleted(object arg) {
            if ((this.buscarVentaPorEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarVentaPorEmpresaCompleted(this, new buscarVentaPorEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarVentaPorFecha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarVentaPorFecha(string fecha1, string fecha2) {
            object[] results = this.Invoke("buscarVentaPorFecha", new object[] {
                        fecha1,
                        fecha2});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarVentaPorFechaAsync(string fecha1, string fecha2) {
            this.buscarVentaPorFechaAsync(fecha1, fecha2, null);
        }
        
        /// <remarks/>
        public void buscarVentaPorFechaAsync(string fecha1, string fecha2, object userState) {
            if ((this.buscarVentaPorFechaOperationCompleted == null)) {
                this.buscarVentaPorFechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarVentaPorFechaOperationCompleted);
            }
            this.InvokeAsync("buscarVentaPorFecha", new object[] {
                        fecha1,
                        fecha2}, this.buscarVentaPorFechaOperationCompleted, userState);
        }
        
        private void OnbuscarVentaPorFechaOperationCompleted(object arg) {
            if ((this.buscarVentaPorFechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarVentaPorFechaCompleted(this, new buscarVentaPorFechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarVentaPorEmpresaCompletedEventHandler(object sender, buscarVentaPorEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarVentaPorEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarVentaPorEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarVentaPorFechaCompletedEventHandler(object sender, buscarVentaPorFechaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarVentaPorFechaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarVentaPorFechaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591